# Generated by Django 5.2.8 on 2025-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_variation_stock_variationcombination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationcombination',
            name='color',
        ),
        migrations.RemoveField(
            model_name='variationcombination',
            name='size',
        ),
        migrations.RemoveField(
            model_name='variationcombination',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='photos/products/'),
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
        migrations.DeleteModel(
            name='VariationCombination',
        ),
    ]
