# Generated by Django 4.2.8 on 2025-11-23 16:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(70)])),
                ('active', models.BooleanField(default=False)),
                ('max_discount_amount', models.PositiveIntegerField(default=0, help_text='Giá trị giảm giá tối đa (VND). Nếu là 0, giảm giá không bị giới hạn tối đa.')),
                ('max_usage_count', models.PositiveIntegerField(default=0, help_text='Tổng số lần tối đa mã có thể được sử dụng (0: Không giới hạn).')),
                ('max_usage_per_customer', models.PositiveIntegerField(default=1, help_text='Số lần tối đa mỗi khách hàng (đã đăng nhập) được sử dụng mã.')),
                ('min_purchase_amount', models.PositiveIntegerField(default=0, help_text='Giá trị đơn hàng tối thiểu (trước giảm giá) để áp dụng mã (0: Không yêu cầu).')),
                ('applies_to', models.CharField(choices=[('ALL', ' TOÀN BỘ '), ('CATEGORY', ' NGÀNH HÀNG')], default='ALL', help_text='Phạm vi áp dụng của mã giảm giá.', max_length=10)),
                ('categories', models.ManyToManyField(blank=True, help_text='Chọn ngành hàng được áp dụng (chỉ dùng khi applies_to = CATEGORY).', to='category.category')),
            ],
            options={
                'verbose_name': 'Coupon Code',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CouponUsage',
                'unique_together': {('coupon', 'user', 'order_id')},
            },
        ),
    ]
