# Generated by Django 4.2.8 on 2025-11-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnimage',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='returns.Return'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='return_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.Return'),
        ),
    ]
