# Generated by Django 4.2.8 on 2025-11-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_last_login_alter_account_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/default_avatar.png', null=True, upload_to='photos/profile/'),
        ),
    ]
