# Generated by Django 4.2.8 on 2025-11-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='VAT',
        ),
    ]
