# Generated by Django 4.2.8 on 2025-11-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderproduct_variations_orderproduct_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing Order', 'Preparing Order'), ('Shipping', 'Shipping'), ('Completed', 'Completed'), ('Returned To Warehouse', 'Returned To Warehouse'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
